sbatch experiment-Copy1.py --SEED 00 --powerestimator power --powerbalance 0.34 --projectname PowerAwareBaseline
sbatch experiment-Copy1.py --SEED 00 --powerestimator power --powerbalance 0.74 --projectname PowerAwareBaseline
sbatch experiment-Copy1.py --SEED 00 --powerestimator power --powerbalance 0.82 --projectname PowerAwareBaseline
sbatch experiment-Copy1.py --SEED 00 --powerestimator power --powerbalance 0.86 --projectname PowerAwareBaseline
sbatch experiment-Copy1.py --SEED 00 --powerestimator power --powerbalance 0.88 --projectname PowerAwareBaseline
sbatch experiment-Copy1.py --SEED 01 --powerestimator power --powerbalance 0.88 --projectname PowerAwareBaseline
sbatch experiment-Copy1.py --SEED 02 --powerestimator power --powerbalance 0.80 --projectname PowerAwareBaseline
sbatch experiment-Copy1.py --SEED 03 --powerestimator power --powerbalance 0.32 --projectname PowerAwareBaseline
sbatch experiment-Copy1.py --SEED 03 --powerestimator power --powerbalance 0.38 --projectname PowerAwareBaseline
sbatch experiment-Copy1.py --SEED 04 --powerestimator power --powerbalance 0.82 --projectname PowerAwareBaseline
sbatch experiment-Copy1.py --SEED 05 --powerestimator power --powerbalance 0.32 --projectname PowerAwareBaseline
sbatch experiment-Copy1.py --SEED 05 --powerestimator power --powerbalance 0.38 --projectname PowerAwareBaseline
sbatch experiment-Copy1.py --SEED 06 --powerestimator power --powerbalance 0.38 --projectname PowerAwareBaseline
sbatch experiment-Copy1.py --SEED 09 --powerestimator power --powerbalance 0.36 --projectname PowerAwareBaseline