sbatch experiment-Copy1.py --SEED 00 --powerestimator power --powerbalance 0.04 --lnc False --projectname PowerAwareBaselineOld
sbatch experiment-Copy1.py --SEED 01 --powerestimator power --powerbalance 0.04 --lnc False --projectname PowerAwareBaselineOld
sbatch experiment-Copy1.py --SEED 02 --powerestimator power --powerbalance 0.00 --lnc False --projectname PowerAwareBaselineOld
sbatch experiment-Copy1.py --SEED 02 --powerestimator power --powerbalance 0.84 --lnc False --projectname PowerAwareBaselineOld
sbatch experiment-Copy1.py --SEED 04 --powerestimator power --powerbalance 0.06 --lnc False --projectname PowerAwareBaselineOld
sbatch experiment-Copy1.py --SEED 05 --powerestimator power --powerbalance 0.04 --lnc False --projectname PowerAwareBaselineOld
sbatch experiment-Copy1.py --SEED 06 --powerestimator power --powerbalance 0.00 --lnc False --projectname PowerAwareBaselineOld
sbatch experiment-Copy1.py --SEED 06 --powerestimator power --powerbalance 0.04 --lnc False --projectname PowerAwareBaselineOld
sbatch experiment-Copy1.py --SEED 06 --powerestimator power --powerbalance 0.84 --lnc False --projectname PowerAwareBaselineOld
sbatch experiment-Copy1.py --SEED 07 --powerestimator power --powerbalance 0.04 --lnc False --projectname PowerAwareBaselineOld
sbatch experiment-Copy1.py --SEED 08 --powerestimator power --powerbalance 0.00 --lnc False --projectname PowerAwareBaselineOld
sbatch experiment-Copy1.py --SEED 09 --powerestimator power --powerbalance 0.04 --lnc False --projectname PowerAwareBaselineOld
sbatch experiment-Copy1.py --SEED 09 --powerestimator power --powerbalance 0.80 --lnc False --projectname PowerAwareBaselineOld